language: php
sudo: required
php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2

env:
  global:
    - CORE_BRANCH=stable10
    - APP_NAME=brute_force_protection
  matrix:
    - DB=sqlite

branches:
  only:
    - master

before_install:
  - which php
  - more $(which pecl)
  - which phpize
  - bash tests/.travis/before_install.sh $APP_NAME $CORE_BRANCH $DB
  - make
  - cd ../core
  - php occ app:enable $APP_NAME

script:
  # check PHP code style
  - cd apps/$APP_NAME
  - composer install
  - vendor/bin/php-cs-fixer fix -v --diff --diff-format udiff --dry-run --allow-risky yes
  # execute unit tests
  - cd tests
  - ../../../lib/composer/phpunit/phpunit/phpunit --configuration phpunit.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)

after_failure:
  - cat ../../data/owncloud.log

matrix:
  include:
    - php: 5.6
      env: DB=mysql
    - php: 7.0
      env: DB=mysql
    - php: 7.1
      env: DB=mysql CORE_BRANCH=master
    - php: 7.1
      env: DB=pgsql CORE_BRANCH=master
    - php: 7.1
      env: DB=oracle CORE_BRANCH=master
    - php: 7.2
      env: DB=mysql CORE_BRANCH=master
    - php: 7.2
      env: DB=pgsql CORE_BRANCH=master
    - php: 7.2
      env: DB=oracle CORE_BRANCH=master
  fast_finish: true